# Day 03

## Problem 1
A report gives many binary numbers. We need gamma rate and epsilon rate. 
Gamma rate: For each position, the value (either 1 or 0 ) which appears most among the given report will be set. 
Epsilon rate: the opposite of the Gamma.
Submit the multiplication of the decimal values of each.

## Example

```
00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
```
This gives;
gamma = 10110, or 22 in decimal
epsilon = 01001, or 9 in decimal
Thus the answer is 22 * 9 = 198.

## Approach

To get a gamma rate, if the total number of "1" for each position is more than half of the total binary numbers given in the report, then the value for that position is to be 1. Otherwise 0.
Epsilon rate is then the opposite.


In [12]:
# make sure how to get the first number as integer
example = "00100"
print(example[0],type(example[0]))
int(example[0])

0 <class 'str'>


0

In [13]:
with open('example.txt','r') as input_text:
    report = input_text.read()
report_list = report.splitlines()
print(report_list)

['00100', '11110', '10110', '10111', '10101', '01111', '00111', '11100', '10000', '11001', '00010', '01010']


In [15]:
# how many bits(?) does each binary value have?
value_size = len(report_list[0])
print(value_size)

5


In [17]:
# how many binary values does the example have?
example_length = len(report_list)
print(example_length)

12


In [28]:
# how to get the first number of the second item in the list?
print(report_list[1][0])

1


In [29]:
# prepare an empty list to store the result binary value (1 or 0) for each position
gamma = []
x = 0
for i in range (0,example_length):
    # to show the value of j-th position of an i-th item in a list is item[i][j]
    x = x + int(report_list[i][0])
print(x)
if x > example_length/2:
    gamma.append(1)
else:
    gamma.append(0)
print(gamma)

7
[1]


In [86]:
gamma = []
# prepare a variable of gamma in binary
gamma_dec = 0
for j in range (0,value_size):
    x = 0
    for i in range (0,example_length):
        x = x + int(report_list[i][j])
        # print(x)
    if x > example_length/2:
        gamma.append(1)
    else:
        gamma.append(0)
print(gamma)

[1, 0, 1, 1, 0]


In [87]:
# try the conversion of binary value to decimal.
# there should be a better way though..
gamma_dec = 1 * pow(2,4) + 0 * pow(2,3) + 1 * pow(2,2) + 1 * pow(2,1) + 0 * pow(2,0)
print(gamma_dec)

22


In [35]:
epsilon = []
epsilon_dec = 0
for j in range (0,value_size):
    x = 0
    for i in range (0,example_length):
        x = x + int(report_list[i][j])
        # print(x)
    if x < example_length/2:
        epsilon.append(1)
    else:
        epsilon.append(0)
    epsilon_dec = epsilon_dec + epsilon[j]*pow(2,value_size-(j+1))
print(epsilon)
print(epsilon_dec)

[0, 1, 0, 0, 1]
9


In [40]:
# try getting both gamma and epsilon at the same time, and get the multiplication of them in decimal in the end.
gamma = []
gamma_dec = 0
epsilon = []
epsilon_dec = 0
for j in range (0,value_size):
    x = 0
    for i in range (0,example_length):
        x = x + int(report_list[i][j])
        # print(x)
    if x < example_length/2:
        epsilon.append(1)
        gamma.append(0)
    else:
        epsilon.append(0)
        gamma.append(1)
    gamma_dec = gamma_dec + gamma[j]*pow(2,value_size-(j+1))
    epsilon_dec = epsilon_dec + epsilon[j]*pow(2,value_size-(j+1))
print("gamma = ", gamma, ", epsilon = ", epsilon)
print("gamma_dec = ", gamma_dec)
print("epsilon_dec = ", epsilon_dec)
answer = gamma_dec * epsilon_dec
print(answer)

gamma =  [1, 0, 1, 1, 0] , epsilon =  [0, 1, 0, 0, 1]
gamma_dec =  22
epsilon_dec =  9
198


In [88]:
# make a function to calculate power consumption
def power_consumption(report_input):
    with open(report_input,'r') as input_text:
        report = input_text.read()
    report_list = report.splitlines()
    value_size = len(report_list[0])
    example_length = len(report_list)
    gamma = []
    gamma_dec = 0
    epsilon = []
    epsilon_dec = 0
    for j in range (0,value_size):
        x = 0
        for i in range (0,example_length):
            x = x + int(report_list[i][j])
            # print(x)
        if x < example_length/2:
            epsilon.append(1)
            gamma.append(0)
        else:
            epsilon.append(0)
            gamma.append(1)
        gamma_dec = gamma_dec + gamma[j]*pow(2,value_size-(j+1))
        epsilon_dec = epsilon_dec + epsilon[j]*pow(2,value_size-(j+1))
    print("gamma = ", gamma, "\n, epsilon = ", epsilon)
    print("gamma_dec = ", gamma_dec)
    print("epsilon_dec = ", epsilon_dec)
    answer = gamma_dec * epsilon_dec
    return(answer)

In [49]:
power_consumption("example.txt")

gamma =  [1, 0, 1, 1, 0] 
, epsilon =  [0, 1, 0, 0, 1]
gamma_dec =  22
epsilon_dec =  9


198

In [50]:
power_consumption("report.txt")

gamma =  [1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0] 
, epsilon =  [0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1]
gamma_dec =  2346
epsilon_dec =  1749


4103154

## Problem 2

We should verify the life support rating, which can be determined by multiplying the oxygen generator rating by the CO2 scrubber rating.

Oxygen generator rating can be obtained in the following manner:

1. compare the count of 1 and 0 of the first bit of each binary value item.
2. items that has the same value to the one that got the most count, or in case if the counts for 0 and 1 are same then the one with 1 in the first bit, will remain.
3. repeat 1 and 2 for the next bit until only 1 item remains.
4. the remaining item in the end in decimal value is the oxygen genrator rating

CO2 scrubber rating can be obtained in the opposite manner to the oxygen generator rating:

1. compare the count of 1 and 0 of the first bit of each binary value item.
2. items that has the same value to the one that got the fewest count, or in case if the counts for 0 and 1 are same then the one with 0 in the first bit, will remain.
3. repeat 1 and 2 for the next bit until only 1 item remains.
4. the remaining item in the end in decimal value is the CO2 scrubber rating

## Example

The same example gives the oxygen generator rating as 10111, or 23 in decimal, and the CO2 scrubber rating as 01010, or 10 in decimal. Therefore, the life support rating is 23 * 10 = 230

### Step 1 and 2

Try with only the first round (the first position) to see how step 1 and 2 could be done.

In [90]:
with open('example.txt','r') as input_text:
    report = input_text.read()
report_list = report.splitlines()
example_length = len(report_list)
x = 0
binary_value = []
for i in range (0,example_length):
    # to show the value of j-th position of an i-th element in a list is element[i][j]
    x = x + int(report_list[i][0])
    # make sure if the x is correct after the for loop is done.
    # print("x = ", x)
# which is the most, either 1 or 0?
if x > example_length/2:
    binary_value.append(1)
else:
    binary_value.append(0)
# make sure if the final result is correct
# print(binary_value[0])
# ---
# check the type of the binary_value[0] 
# as the for loop with if inside the list below (oxgen_candidates) did not go well first.
# (of course) as the items in the report_list was not converted to int, it remains as str. 
# so it needs to be converted to int.
# ---
# print("type of binary_value = ", type(binary_value[0]))
# print(type(report_list[0][0]))
oxgen_candidates = [oxgen_item for oxgen_item in report_list if int(oxgen_item[0]) == binary_value[0]]
print(oxgen_candidates)

['11110', '10110', '10111', '10101', '11100', '10000', '11001']


### Step 3 and 4

First try with oxgen generator rating. 

In [91]:
with open('example.txt','r') as input_text:
    report = input_text.read()
report_list = report.splitlines()
# separate a list of original data and a list that changes in the course of finding process
item_list = report_list
value_size = len(report_list[0])
example_length = len(report_list)
# separate the lenth of original data and that of a list that changes in the course of finding process
total_items = example_length
binary_value = []
oxgen_rating = 0
# as "value_size" is anyways the max of the repetition, probably it is OK to use it rather than using while?
for j in range (0, value_size):
    x = 0
    for i in range (0,total_items):
        # to show the value of j-th position of an i-th element in a list is element[i][j]
        x = x + int(item_list[i][j])
    # which is the most, either 1 or 0?
    if x >= total_items/2:
        binary_value.append(1)
    else:
        binary_value.append(0)
    oxgen_candidates = [oxgen_item for oxgen_item in item_list if int(oxgen_item[j]) == binary_value[j]]
    item_list = oxgen_candidates
    total_items = len(item_list)
    if len(item_list) == 1:
        print(item_list) 
        break
for j in range (0, value_size):
    oxgen_rating = oxgen_rating + int(item_list[0][j])*pow(2,value_size-(j+1))
print("oxgen_rating is ", oxgen_rating)

['10111']
oxgen_rating is  23


In [92]:
with open('example.txt','r') as input_text:
    report = input_text.read()
report_list = report.splitlines()
# separate a list of original data and a list that changes in the course of finding process
item_list = report_list
value_size = len(report_list[0])
example_length = len(report_list)
# separate the lenth of original data and that of a list that changes in the course of finding process
total_items = example_length
binary_value = []
co2_rating = 0
# as "value_size" is anyways the max of the repetition, probably it is OK to use it rather than using while?
for j in range (0, value_size):
    x = 0
    for i in range (0,total_items):
        # to show the value of j-th position of an i-th element in a list is element[i][j]
        x = x + int(item_list[i][j])
    # which is the most, either 1 or 0?
    if x >= total_items/2:
        binary_value.append(0)
    else:
        binary_value.append(1)
    co2_candidates = [co2_item for co2_item in item_list if int(co2_item[j]) == binary_value[j]]
    item_list = co2_candidates
    total_items = len(item_list)
    if len(item_list) == 1:
        print(item_list) 
        break
for j in range (0, value_size):
    co2_rating = co2_rating + int(item_list[0][j])*pow(2,value_size-(j+1))
print("co2_rating is ", co2_rating)

['01010']
co2_rating is  10


### Making this into functions with arguments of 1. input file, 2. type of rating

In [81]:
def find_rating(report_input, mode):
    with open(report_input,'r') as input_text:
        report = input_text.read()
    report_list = report.splitlines()
    # separate a list of original data and a list that changes in the course of finding process
    item_list = report_list
    value_size = len(report_list[0])
    example_length = len(report_list)
    # separate the lenth of original data and that of a list that changes in the course of finding process
    total_items = example_length
    binary_value = []
    rating = 0
    # as "value_size" is anyways the max of the repetition, probably it is OK to use it rather than using while?
    for j in range (0, value_size):
        x = 0
        for i in range (0,total_items):
            # to show the value of j-th position of an i-th element in a list is element[i][j]
            x = x + int(item_list[i][j])
        # which is the most, either 1 or 0?
        if mode == "co2":
            if x >= total_items/2:
                binary_value.append(0)
            else:
                binary_value.append(1)
        else:
            if x >= total_items/2:
                binary_value.append(1)
            else:
                binary_value.append(0)            
        candidates = [item for item in item_list if int(item[j]) == binary_value[j]]
        item_list = candidates
        total_items = len(item_list)
        if len(item_list) == 1:
            print(item_list) 
            break
    for j in range (0, value_size):
        rating = rating + int(item_list[0][j])*pow(2,value_size-(j+1))
    if mode == "co2":
        print("co2_rating is ", rating)
    else:
        print("oxgen_rating is ", rating)
    return(rating)

In [82]:
find_rating("example.txt","co2")

['01010']
co2_rating is  10


10

In [83]:
find_rating("example.txt","oxgen")

['10111']
oxgen_rating is  23


23

In [85]:
life_support_rating = find_rating("report.txt","oxgen")*find_rating("report.txt","co2")
print(life_support_rating)

['110101000111']
oxgen_rating is  3399
['010011100001']
co2_rating is  1249
4245351
